// Generated by gencpp from file iserve_msgs/Position_cv_anmo.msg
// DO NOT EDIT!


#ifndef ISERVE_MSGS_MESSAGE_POSITION_CV_ANMO_H
#define ISERVE_MSGS_MESSAGE_POSITION_CV_ANMO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iserve_msgs
{
template <class ContainerAllocator>
struct Position_cv_anmo_
{
  typedef Position_cv_anmo_<ContainerAllocator> Type;

  Position_cv_anmo_()
    : stamp()
    , isdone(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Position_cv_anmo_(const ContainerAllocator& _alloc)
    : stamp()
    , isdone(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _isdone_type;
  _isdone_type isdone;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> const> ConstPtr;

}; // struct Position_cv_anmo_

typedef ::iserve_msgs::Position_cv_anmo_<std::allocator<void> > Position_cv_anmo;

typedef boost::shared_ptr< ::iserve_msgs::Position_cv_anmo > Position_cv_anmoPtr;
typedef boost::shared_ptr< ::iserve_msgs::Position_cv_anmo const> Position_cv_anmoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator1> & lhs, const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.isdone == rhs.isdone &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator1> & lhs, const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iserve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4564bfea93f9586cd3dad5d4be058467";
  }

  static const char* value(const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4564bfea93f9586cULL;
  static const uint64_t static_value2 = 0xd3dad5d4be058467ULL;
};

template<class ContainerAllocator>
struct DataType< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iserve_msgs/Position_cv_anmo";
  }

  static const char* value(const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float32 isdone\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.isdone);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_cv_anmo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iserve_msgs::Position_cv_anmo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iserve_msgs::Position_cv_anmo_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "isdone: ";
    Printer<float>::stream(s, indent + "  ", v.isdone);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISERVE_MSGS_MESSAGE_POSITION_CV_ANMO_H
