// Generated by gencpp from file iserve_msgs/TaskStatus.msg
// DO NOT EDIT!


#ifndef ISERVE_MSGS_MESSAGE_TASKSTATUS_H
#define ISERVE_MSGS_MESSAGE_TASKSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iserve_msgs
{
template <class ContainerAllocator>
struct TaskStatus_
{
  typedef TaskStatus_<ContainerAllocator> Type;

  TaskStatus_()
    : header()
    , seq(0)
    , stamp()
    , frame_id()
    , task_id()
    , isbusy(false)  {
    }
  TaskStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seq(0)
    , stamp()
    , frame_id(_alloc)
    , task_id(_alloc)
    , isbusy(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef uint8_t _isbusy_type;
  _isbusy_type isbusy;





  typedef boost::shared_ptr< ::iserve_msgs::TaskStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iserve_msgs::TaskStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskStatus_

typedef ::iserve_msgs::TaskStatus_<std::allocator<void> > TaskStatus;

typedef boost::shared_ptr< ::iserve_msgs::TaskStatus > TaskStatusPtr;
typedef boost::shared_ptr< ::iserve_msgs::TaskStatus const> TaskStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iserve_msgs::TaskStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iserve_msgs::TaskStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iserve_msgs::TaskStatus_<ContainerAllocator1> & lhs, const ::iserve_msgs::TaskStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.seq == rhs.seq &&
    lhs.stamp == rhs.stamp &&
    lhs.frame_id == rhs.frame_id &&
    lhs.task_id == rhs.task_id &&
    lhs.isbusy == rhs.isbusy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iserve_msgs::TaskStatus_<ContainerAllocator1> & lhs, const ::iserve_msgs::TaskStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iserve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iserve_msgs::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_msgs::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_msgs::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c31503d99ebfd77d8682c6ab09a263aa";
  }

  static const char* value(const ::iserve_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc31503d99ebfd77dULL;
  static const uint64_t static_value2 = 0x8682c6ab09a263aaULL;
};

template<class ContainerAllocator>
struct DataType< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iserve_msgs/TaskStatus";
  }

  static const char* value(const ::iserve_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"  uint32 seq\n"
"  time stamp\n"
"  string frame_id\n"
"string  task_id\n"
"bool isbusy\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::iserve_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seq);
      stream.next(m.stamp);
      stream.next(m.frame_id);
      stream.next(m.task_id);
      stream.next(m.isbusy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iserve_msgs::TaskStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iserve_msgs::TaskStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    s << indent << "isbusy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isbusy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISERVE_MSGS_MESSAGE_TASKSTATUS_H
