(cl:in-package iserve_srvs-srv)
(cl:export '(TESTITEM-VAL
          TESTITEM
          ISLOAD-VAL
          ISLOAD
          ISSINGLEJOINT-VAL
          ISSINGLEJOINT
          JOINTNO-VAL
          JOINTNO
          CYCLETIMES-VAL
          CYCLETIMES
          VELOCITY-VAL
          VELOCITY
          POINTINDEX-VAL
          POINTINDEX
          SEGMENTNO-VAL
          SEGMENTNO
          STARTINDEX-VAL
          STARTINDEX
          ENDINDEX-VAL
          ENDINDEX
          SUCCESS-VAL
          SUCCESS
          TESTITEM-VAL
          TESTITEM
          ISLOAD-VAL
          ISLOAD
          CYCLETIMES-VAL
          CYCLETIMES
          VELOCITY-VAL
          VELOCITY
          ISSINGLEJOINT-VAL
          ISSINGLEJOINT
          JOINTNO-VAL
          JOINTNO
          SEGMENTNO-VAL
          SEGMENTNO
          POINTINDEX-VAL
          POINTINDEX
          STARTINDEX-VAL
          STARTINDEX
          ENDINDEX-VAL
          ENDINDEX
))