// Generated by gencpp from file iserve_srvs/DeliveryRobotTaskResponse.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_DELIVERYROBOTTASKRESPONSE_H
#define ISERVE_SRVS_MESSAGE_DELIVERYROBOTTASKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iserve_srvs
{
template <class ContainerAllocator>
struct DeliveryRobotTaskResponse_
{
  typedef DeliveryRobotTaskResponse_<ContainerAllocator> Type;

  DeliveryRobotTaskResponse_()
    : success(false)
    , message()  {
    }
  DeliveryRobotTaskResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeliveryRobotTaskResponse_

typedef ::iserve_srvs::DeliveryRobotTaskResponse_<std::allocator<void> > DeliveryRobotTaskResponse;

typedef boost::shared_ptr< ::iserve_srvs::DeliveryRobotTaskResponse > DeliveryRobotTaskResponsePtr;
typedef boost::shared_ptr< ::iserve_srvs::DeliveryRobotTaskResponse const> DeliveryRobotTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator1> & lhs, const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator1> & lhs, const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iserve_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iserve_srvs/DeliveryRobotTaskResponse";
  }

  static const char* value(const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success         #反馈服务是否调用成功\n"
"string message       #相关的comment\n"
"\n"
;
  }

  static const char* value(const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeliveryRobotTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iserve_srvs::DeliveryRobotTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_DELIVERYROBOTTASKRESPONSE_H
