// Generated by gencpp from file iserve_srvs/DeliveryRobotTask.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_DELIVERYROBOTTASK_H
#define ISERVE_SRVS_MESSAGE_DELIVERYROBOTTASK_H

#include <ros/service_traits.h>


#include <iserve_srvs/DeliveryRobotTaskRequest.h>
#include <iserve_srvs/DeliveryRobotTaskResponse.h>


namespace iserve_srvs
{

struct DeliveryRobotTask
{

typedef DeliveryRobotTaskRequest Request;
typedef DeliveryRobotTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeliveryRobotTask
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::DeliveryRobotTask > {
  static const char* value()
  {
    return "1d4bbb7bd00384e7a69a86662cfc883c";
  }

  static const char* value(const ::iserve_srvs::DeliveryRobotTask&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::DeliveryRobotTask > {
  static const char* value()
  {
    return "iserve_srvs/DeliveryRobotTask";
  }

  static const char* value(const ::iserve_srvs::DeliveryRobotTask&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::DeliveryRobotTaskRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::DeliveryRobotTask >
template<>
struct MD5Sum< ::iserve_srvs::DeliveryRobotTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::DeliveryRobotTask >::value();
  }
  static const char* value(const ::iserve_srvs::DeliveryRobotTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::DeliveryRobotTaskRequest> should match
// service_traits::DataType< ::iserve_srvs::DeliveryRobotTask >
template<>
struct DataType< ::iserve_srvs::DeliveryRobotTaskRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::DeliveryRobotTask >::value();
  }
  static const char* value(const ::iserve_srvs::DeliveryRobotTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::DeliveryRobotTaskResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::DeliveryRobotTask >
template<>
struct MD5Sum< ::iserve_srvs::DeliveryRobotTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::DeliveryRobotTask >::value();
  }
  static const char* value(const ::iserve_srvs::DeliveryRobotTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::DeliveryRobotTaskResponse> should match
// service_traits::DataType< ::iserve_srvs::DeliveryRobotTask >
template<>
struct DataType< ::iserve_srvs::DeliveryRobotTaskResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::DeliveryRobotTask >::value();
  }
  static const char* value(const ::iserve_srvs::DeliveryRobotTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_DELIVERYROBOTTASK_H
