// Generated by gencpp from file iserve_srvs/DragTeach.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_DRAGTEACH_H
#define ISERVE_SRVS_MESSAGE_DRAGTEACH_H

#include <ros/service_traits.h>


#include <iserve_srvs/DragTeachRequest.h>
#include <iserve_srvs/DragTeachResponse.h>


namespace iserve_srvs
{

struct DragTeach
{

typedef DragTeachRequest Request;
typedef DragTeachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DragTeach
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::DragTeach > {
  static const char* value()
  {
    return "0ec3616815302eee28b553178a1eed29";
  }

  static const char* value(const ::iserve_srvs::DragTeach&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::DragTeach > {
  static const char* value()
  {
    return "iserve_srvs/DragTeach";
  }

  static const char* value(const ::iserve_srvs::DragTeach&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::DragTeachRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::DragTeach >
template<>
struct MD5Sum< ::iserve_srvs::DragTeachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::DragTeach >::value();
  }
  static const char* value(const ::iserve_srvs::DragTeachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::DragTeachRequest> should match
// service_traits::DataType< ::iserve_srvs::DragTeach >
template<>
struct DataType< ::iserve_srvs::DragTeachRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::DragTeach >::value();
  }
  static const char* value(const ::iserve_srvs::DragTeachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::DragTeachResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::DragTeach >
template<>
struct MD5Sum< ::iserve_srvs::DragTeachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::DragTeach >::value();
  }
  static const char* value(const ::iserve_srvs::DragTeachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::DragTeachResponse> should match
// service_traits::DataType< ::iserve_srvs::DragTeach >
template<>
struct DataType< ::iserve_srvs::DragTeachResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::DragTeach >::value();
  }
  static const char* value(const ::iserve_srvs::DragTeachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_DRAGTEACH_H
