// Generated by gencpp from file iserve_srvs/Enable_cv_anmo.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_ENABLE_CV_ANMO_H
#define ISERVE_SRVS_MESSAGE_ENABLE_CV_ANMO_H

#include <ros/service_traits.h>


#include <iserve_srvs/Enable_cv_anmoRequest.h>
#include <iserve_srvs/Enable_cv_anmoResponse.h>


namespace iserve_srvs
{

struct Enable_cv_anmo
{

typedef Enable_cv_anmoRequest Request;
typedef Enable_cv_anmoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Enable_cv_anmo
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::Enable_cv_anmo > {
  static const char* value()
  {
    return "e1e111322e6a2085adde944da2f908ec";
  }

  static const char* value(const ::iserve_srvs::Enable_cv_anmo&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::Enable_cv_anmo > {
  static const char* value()
  {
    return "iserve_srvs/Enable_cv_anmo";
  }

  static const char* value(const ::iserve_srvs::Enable_cv_anmo&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::Enable_cv_anmoRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::Enable_cv_anmo >
template<>
struct MD5Sum< ::iserve_srvs::Enable_cv_anmoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::Enable_cv_anmo >::value();
  }
  static const char* value(const ::iserve_srvs::Enable_cv_anmoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::Enable_cv_anmoRequest> should match
// service_traits::DataType< ::iserve_srvs::Enable_cv_anmo >
template<>
struct DataType< ::iserve_srvs::Enable_cv_anmoRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::Enable_cv_anmo >::value();
  }
  static const char* value(const ::iserve_srvs::Enable_cv_anmoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::Enable_cv_anmoResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::Enable_cv_anmo >
template<>
struct MD5Sum< ::iserve_srvs::Enable_cv_anmoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::Enable_cv_anmo >::value();
  }
  static const char* value(const ::iserve_srvs::Enable_cv_anmoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::Enable_cv_anmoResponse> should match
// service_traits::DataType< ::iserve_srvs::Enable_cv_anmo >
template<>
struct DataType< ::iserve_srvs::Enable_cv_anmoResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::Enable_cv_anmo >::value();
  }
  static const char* value(const ::iserve_srvs::Enable_cv_anmoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_ENABLE_CV_ANMO_H
