// Generated by gencpp from file iserve_srvs/ImpedanceTask.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_IMPEDANCETASK_H
#define ISERVE_SRVS_MESSAGE_IMPEDANCETASK_H

#include <ros/service_traits.h>


#include <iserve_srvs/ImpedanceTaskRequest.h>
#include <iserve_srvs/ImpedanceTaskResponse.h>


namespace iserve_srvs
{

struct ImpedanceTask
{

typedef ImpedanceTaskRequest Request;
typedef ImpedanceTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImpedanceTask
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::ImpedanceTask > {
  static const char* value()
  {
    return "21908f874f4e6cb2dd60a1908a933187";
  }

  static const char* value(const ::iserve_srvs::ImpedanceTask&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::ImpedanceTask > {
  static const char* value()
  {
    return "iserve_srvs/ImpedanceTask";
  }

  static const char* value(const ::iserve_srvs::ImpedanceTask&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::ImpedanceTaskRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::ImpedanceTask >
template<>
struct MD5Sum< ::iserve_srvs::ImpedanceTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::ImpedanceTask >::value();
  }
  static const char* value(const ::iserve_srvs::ImpedanceTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::ImpedanceTaskRequest> should match
// service_traits::DataType< ::iserve_srvs::ImpedanceTask >
template<>
struct DataType< ::iserve_srvs::ImpedanceTaskRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::ImpedanceTask >::value();
  }
  static const char* value(const ::iserve_srvs::ImpedanceTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::ImpedanceTaskResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::ImpedanceTask >
template<>
struct MD5Sum< ::iserve_srvs::ImpedanceTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::ImpedanceTask >::value();
  }
  static const char* value(const ::iserve_srvs::ImpedanceTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::ImpedanceTaskResponse> should match
// service_traits::DataType< ::iserve_srvs::ImpedanceTask >
template<>
struct DataType< ::iserve_srvs::ImpedanceTaskResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::ImpedanceTask >::value();
  }
  static const char* value(const ::iserve_srvs::ImpedanceTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_IMPEDANCETASK_H
