// Generated by gencpp from file iserve_srvs/JointPose.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_JOINTPOSE_H
#define ISERVE_SRVS_MESSAGE_JOINTPOSE_H

#include <ros/service_traits.h>


#include <iserve_srvs/JointPoseRequest.h>
#include <iserve_srvs/JointPoseResponse.h>


namespace iserve_srvs
{

struct JointPose
{

typedef JointPoseRequest Request;
typedef JointPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointPose
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::JointPose > {
  static const char* value()
  {
    return "949fbcedff97c69401016e18f534c384";
  }

  static const char* value(const ::iserve_srvs::JointPose&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::JointPose > {
  static const char* value()
  {
    return "iserve_srvs/JointPose";
  }

  static const char* value(const ::iserve_srvs::JointPose&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::JointPoseRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::JointPose >
template<>
struct MD5Sum< ::iserve_srvs::JointPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::JointPose >::value();
  }
  static const char* value(const ::iserve_srvs::JointPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::JointPoseRequest> should match
// service_traits::DataType< ::iserve_srvs::JointPose >
template<>
struct DataType< ::iserve_srvs::JointPoseRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::JointPose >::value();
  }
  static const char* value(const ::iserve_srvs::JointPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::JointPoseResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::JointPose >
template<>
struct MD5Sum< ::iserve_srvs::JointPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::JointPose >::value();
  }
  static const char* value(const ::iserve_srvs::JointPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::JointPoseResponse> should match
// service_traits::DataType< ::iserve_srvs::JointPose >
template<>
struct DataType< ::iserve_srvs::JointPoseResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::JointPose >::value();
  }
  static const char* value(const ::iserve_srvs::JointPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_JOINTPOSE_H
