// Generated by gencpp from file iserve_srvs/PlanSwitch.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_PLANSWITCH_H
#define ISERVE_SRVS_MESSAGE_PLANSWITCH_H

#include <ros/service_traits.h>


#include <iserve_srvs/PlanSwitchRequest.h>
#include <iserve_srvs/PlanSwitchResponse.h>


namespace iserve_srvs
{

struct PlanSwitch
{

typedef PlanSwitchRequest Request;
typedef PlanSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanSwitch
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::PlanSwitch > {
  static const char* value()
  {
    return "cfeabc4c78e5fd8d5dc411ef1421855a";
  }

  static const char* value(const ::iserve_srvs::PlanSwitch&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::PlanSwitch > {
  static const char* value()
  {
    return "iserve_srvs/PlanSwitch";
  }

  static const char* value(const ::iserve_srvs::PlanSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::PlanSwitchRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::PlanSwitch >
template<>
struct MD5Sum< ::iserve_srvs::PlanSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::PlanSwitch >::value();
  }
  static const char* value(const ::iserve_srvs::PlanSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::PlanSwitchRequest> should match
// service_traits::DataType< ::iserve_srvs::PlanSwitch >
template<>
struct DataType< ::iserve_srvs::PlanSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::PlanSwitch >::value();
  }
  static const char* value(const ::iserve_srvs::PlanSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::PlanSwitchResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::PlanSwitch >
template<>
struct MD5Sum< ::iserve_srvs::PlanSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::PlanSwitch >::value();
  }
  static const char* value(const ::iserve_srvs::PlanSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::PlanSwitchResponse> should match
// service_traits::DataType< ::iserve_srvs::PlanSwitch >
template<>
struct DataType< ::iserve_srvs::PlanSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::PlanSwitch >::value();
  }
  static const char* value(const ::iserve_srvs::PlanSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_PLANSWITCH_H
