// Generated by gencpp from file iserve_srvs/SetIntRequest.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_SETINTREQUEST_H
#define ISERVE_SRVS_MESSAGE_SETINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iserve_srvs
{
template <class ContainerAllocator>
struct SetIntRequest_
{
  typedef SetIntRequest_<ContainerAllocator> Type;

  SetIntRequest_()
    : input(0)  {
    }
  SetIntRequest_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int64_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::iserve_srvs::SetIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iserve_srvs::SetIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIntRequest_

typedef ::iserve_srvs::SetIntRequest_<std::allocator<void> > SetIntRequest;

typedef boost::shared_ptr< ::iserve_srvs::SetIntRequest > SetIntRequestPtr;
typedef boost::shared_ptr< ::iserve_srvs::SetIntRequest const> SetIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iserve_srvs::SetIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iserve_srvs::SetIntRequest_<ContainerAllocator1> & lhs, const ::iserve_srvs::SetIntRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iserve_srvs::SetIntRequest_<ContainerAllocator1> & lhs, const ::iserve_srvs::SetIntRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iserve_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::SetIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::SetIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::SetIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb1911a9ea9163151d70e4586fa0801";
  }

  static const char* value(const ::iserve_srvs::SetIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb1911a9ea91631ULL;
  static const uint64_t static_value2 = 0x51d70e4586fa0801ULL;
};

template<class ContainerAllocator>
struct DataType< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iserve_srvs/SetIntRequest";
  }

  static const char* value(const ::iserve_srvs::SetIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 input\n"
;
  }

  static const char* value(const ::iserve_srvs::SetIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iserve_srvs::SetIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iserve_srvs::SetIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_SETINTREQUEST_H
