// Generated by gencpp from file iserve_srvs/SetIntResponse.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_SETINTRESPONSE_H
#define ISERVE_SRVS_MESSAGE_SETINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iserve_srvs
{
template <class ContainerAllocator>
struct SetIntResponse_
{
  typedef SetIntResponse_<ContainerAllocator> Type;

  SetIntResponse_()
    : output(0)  {
    }
  SetIntResponse_(const ContainerAllocator& _alloc)
    : output(0)  {
  (void)_alloc;
    }



   typedef int64_t _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::iserve_srvs::SetIntResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iserve_srvs::SetIntResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetIntResponse_

typedef ::iserve_srvs::SetIntResponse_<std::allocator<void> > SetIntResponse;

typedef boost::shared_ptr< ::iserve_srvs::SetIntResponse > SetIntResponsePtr;
typedef boost::shared_ptr< ::iserve_srvs::SetIntResponse const> SetIntResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iserve_srvs::SetIntResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iserve_srvs::SetIntResponse_<ContainerAllocator1> & lhs, const ::iserve_srvs::SetIntResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iserve_srvs::SetIntResponse_<ContainerAllocator1> & lhs, const ::iserve_srvs::SetIntResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iserve_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::SetIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::SetIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::SetIntResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf29e6e649dbd18239f4c3f12579de7";
  }

  static const char* value(const ::iserve_srvs::SetIntResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf29e6e649dbd18ULL;
  static const uint64_t static_value2 = 0x239f4c3f12579de7ULL;
};

template<class ContainerAllocator>
struct DataType< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iserve_srvs/SetIntResponse";
  }

  static const char* value(const ::iserve_srvs::SetIntResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 output\n"
"\n"
"\n"
;
  }

  static const char* value(const ::iserve_srvs::SetIntResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIntResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iserve_srvs::SetIntResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iserve_srvs::SetIntResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int64_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_SETINTRESPONSE_H
