// Generated by gencpp from file iserve_srvs/SetInt.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_SETINT_H
#define ISERVE_SRVS_MESSAGE_SETINT_H

#include <ros/service_traits.h>


#include <iserve_srvs/SetIntRequest.h>
#include <iserve_srvs/SetIntResponse.h>


namespace iserve_srvs
{

struct SetInt
{

typedef SetIntRequest Request;
typedef SetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::SetInt > {
  static const char* value()
  {
    return "9cc62145209219f185101e72e3ae5c65";
  }

  static const char* value(const ::iserve_srvs::SetInt&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::SetInt > {
  static const char* value()
  {
    return "iserve_srvs/SetInt";
  }

  static const char* value(const ::iserve_srvs::SetInt&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::SetIntRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::SetInt >
template<>
struct MD5Sum< ::iserve_srvs::SetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::SetInt >::value();
  }
  static const char* value(const ::iserve_srvs::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::SetIntRequest> should match
// service_traits::DataType< ::iserve_srvs::SetInt >
template<>
struct DataType< ::iserve_srvs::SetIntRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::SetInt >::value();
  }
  static const char* value(const ::iserve_srvs::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::SetIntResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::SetInt >
template<>
struct MD5Sum< ::iserve_srvs::SetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::SetInt >::value();
  }
  static const char* value(const ::iserve_srvs::SetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::SetIntResponse> should match
// service_traits::DataType< ::iserve_srvs::SetInt >
template<>
struct DataType< ::iserve_srvs::SetIntResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::SetInt >::value();
  }
  static const char* value(const ::iserve_srvs::SetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_SETINT_H
