// Generated by gencpp from file iserve_srvs/TestCommandRequest.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_TESTCOMMANDREQUEST_H
#define ISERVE_SRVS_MESSAGE_TESTCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iserve_srvs
{
template <class ContainerAllocator>
struct TestCommandRequest_
{
  typedef TestCommandRequest_<ContainerAllocator> Type;

  TestCommandRequest_()
    : testItem()
    , isLoad(false)
    , isSingleJoint(false)
    , jointNo(0)
    , cycleTimes(0)
    , velocity(0.0)
    , pointIndex(0)
    , segmentNo()
    , startIndex(0)
    , endIndex(0)  {
    }
  TestCommandRequest_(const ContainerAllocator& _alloc)
    : testItem(_alloc)
    , isLoad(false)
    , isSingleJoint(false)
    , jointNo(0)
    , cycleTimes(0)
    , velocity(0.0)
    , pointIndex(0)
    , segmentNo(_alloc)
    , startIndex(0)
    , endIndex(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _testItem_type;
  _testItem_type testItem;

   typedef uint8_t _isLoad_type;
  _isLoad_type isLoad;

   typedef uint8_t _isSingleJoint_type;
  _isSingleJoint_type isSingleJoint;

   typedef int32_t _jointNo_type;
  _jointNo_type jointNo;

   typedef int32_t _cycleTimes_type;
  _cycleTimes_type cycleTimes;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef int32_t _pointIndex_type;
  _pointIndex_type pointIndex;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _segmentNo_type;
  _segmentNo_type segmentNo;

   typedef int32_t _startIndex_type;
  _startIndex_type startIndex;

   typedef int32_t _endIndex_type;
  _endIndex_type endIndex;





  typedef boost::shared_ptr< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TestCommandRequest_

typedef ::iserve_srvs::TestCommandRequest_<std::allocator<void> > TestCommandRequest;

typedef boost::shared_ptr< ::iserve_srvs::TestCommandRequest > TestCommandRequestPtr;
typedef boost::shared_ptr< ::iserve_srvs::TestCommandRequest const> TestCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iserve_srvs::TestCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iserve_srvs::TestCommandRequest_<ContainerAllocator1> & lhs, const ::iserve_srvs::TestCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.testItem == rhs.testItem &&
    lhs.isLoad == rhs.isLoad &&
    lhs.isSingleJoint == rhs.isSingleJoint &&
    lhs.jointNo == rhs.jointNo &&
    lhs.cycleTimes == rhs.cycleTimes &&
    lhs.velocity == rhs.velocity &&
    lhs.pointIndex == rhs.pointIndex &&
    lhs.segmentNo == rhs.segmentNo &&
    lhs.startIndex == rhs.startIndex &&
    lhs.endIndex == rhs.endIndex;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iserve_srvs::TestCommandRequest_<ContainerAllocator1> & lhs, const ::iserve_srvs::TestCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iserve_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fa6b05583c7b8dd0dddb40da0b1f6ba";
  }

  static const char* value(const ::iserve_srvs::TestCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fa6b05583c7b8ddULL;
  static const uint64_t static_value2 = 0x0dddb40da0b1f6baULL;
};

template<class ContainerAllocator>
struct DataType< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iserve_srvs/TestCommandRequest";
  }

  static const char* value(const ::iserve_srvs::TestCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#noiseTest, motionStabilityTest, loadTest, jointAngleTest, accuracyTest, powTest, breakTest, motionTest, goHome\n"
"string testItem\n"
"\n"
"bool isLoad\n"
"bool isSingleJoint\n"
"\n"
"#0, 1, 2, 3, 4, 5\n"
"int32 jointNo\n"
"\n"
"# at least 1\n"
"int32 cycleTimes\n"
"float64 velocity\n"
"\n"
"# 1, 2, 3, 4, 5\n"
"int32 pointIndex\n"
"\n"
"#toShelf, toLocker, goHome\n"
"string segmentNo\n"
"\n"
"int32 startIndex\n"
"int32 endIndex\n"
;
  }

  static const char* value(const ::iserve_srvs::TestCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.testItem);
      stream.next(m.isLoad);
      stream.next(m.isSingleJoint);
      stream.next(m.jointNo);
      stream.next(m.cycleTimes);
      stream.next(m.velocity);
      stream.next(m.pointIndex);
      stream.next(m.segmentNo);
      stream.next(m.startIndex);
      stream.next(m.endIndex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iserve_srvs::TestCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iserve_srvs::TestCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "testItem: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.testItem);
    s << indent << "isLoad: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isLoad);
    s << indent << "isSingleJoint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSingleJoint);
    s << indent << "jointNo: ";
    Printer<int32_t>::stream(s, indent + "  ", v.jointNo);
    s << indent << "cycleTimes: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cycleTimes);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "pointIndex: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pointIndex);
    s << indent << "segmentNo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.segmentNo);
    s << indent << "startIndex: ";
    Printer<int32_t>::stream(s, indent + "  ", v.startIndex);
    s << indent << "endIndex: ";
    Printer<int32_t>::stream(s, indent + "  ", v.endIndex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_TESTCOMMANDREQUEST_H
