// Generated by gencpp from file iserve_srvs/TestCommand.msg
// DO NOT EDIT!


#ifndef ISERVE_SRVS_MESSAGE_TESTCOMMAND_H
#define ISERVE_SRVS_MESSAGE_TESTCOMMAND_H

#include <ros/service_traits.h>


#include <iserve_srvs/TestCommandRequest.h>
#include <iserve_srvs/TestCommandResponse.h>


namespace iserve_srvs
{

struct TestCommand
{

typedef TestCommandRequest Request;
typedef TestCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TestCommand
} // namespace iserve_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iserve_srvs::TestCommand > {
  static const char* value()
  {
    return "56cbc0917dc3153d523ed8899f37edfb";
  }

  static const char* value(const ::iserve_srvs::TestCommand&) { return value(); }
};

template<>
struct DataType< ::iserve_srvs::TestCommand > {
  static const char* value()
  {
    return "iserve_srvs/TestCommand";
  }

  static const char* value(const ::iserve_srvs::TestCommand&) { return value(); }
};


// service_traits::MD5Sum< ::iserve_srvs::TestCommandRequest> should match
// service_traits::MD5Sum< ::iserve_srvs::TestCommand >
template<>
struct MD5Sum< ::iserve_srvs::TestCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::TestCommand >::value();
  }
  static const char* value(const ::iserve_srvs::TestCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::TestCommandRequest> should match
// service_traits::DataType< ::iserve_srvs::TestCommand >
template<>
struct DataType< ::iserve_srvs::TestCommandRequest>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::TestCommand >::value();
  }
  static const char* value(const ::iserve_srvs::TestCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iserve_srvs::TestCommandResponse> should match
// service_traits::MD5Sum< ::iserve_srvs::TestCommand >
template<>
struct MD5Sum< ::iserve_srvs::TestCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iserve_srvs::TestCommand >::value();
  }
  static const char* value(const ::iserve_srvs::TestCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iserve_srvs::TestCommandResponse> should match
// service_traits::DataType< ::iserve_srvs::TestCommand >
template<>
struct DataType< ::iserve_srvs::TestCommandResponse>
{
  static const char* value()
  {
    return DataType< ::iserve_srvs::TestCommand >::value();
  }
  static const char* value(const ::iserve_srvs::TestCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISERVE_SRVS_MESSAGE_TESTCOMMAND_H
